name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v1

    - name: Build
      run: |
        perl -v
        make

    - name: Run minimal test
      run: |
        source built/count.sh
        echo -e 'a\nb\na' | cnt

    - name: Run tests
      run: |
        cd test
        bash run.bash
